deployment:
  appType: python-multi-jobs
  appId: appXXXXXXXX
  namespace: appXXXXXXXX-cribl-elk-psql
  serviceName: cribl-framework
  port: 5000
  replicas: 1
  healthCheck: /cribl/health
  volumes:
    - name: config-volume
      secret:
        secretName: cribl-framework-appconfig
  volumeMounts:
    - name: config-volume
      mountPath: /app/config.json
      subPath: config.json
      readOnly: true
  env:
    - name: LOG_LEVEL
      value: INFO
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: database-url
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: secret-key
    - name: ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: admin-username
    - name: ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: admin-password
    - name: ES_DATASTREAM_URL
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: es-datastream-url
    - name: ES_DATASTREAM_USERNAME
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: es-datastream-username
    - name: ES_DATASTREAM_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: es-datastream-password
    - name: ENT_ES_CLUSTERS
      valueFrom:
        secretKeyRef:
          name: cribl-elk-psql-secrets
          key: ent-es-clusters
    - name: CRIBL_SERVICE_URL
      value: http://cribl-service:8001
    - name: ECE_SERVICE_URL
      value: http://ece-service:8002
    - name: ETN_ONBOARDING_URL
      value: http://etn-onboarding:5000
