#!/usr/bin/env bash
# Run untracked apmIds audit and email the results.
#
# Usage:
#   ./send_report.sh -t recipient@example.com [-c config.json] [-d 7]

set -euo pipefail

# --- defaults ----------------------------------------------------------------
CONFIG="config.json"
DAYS=7
FROM="${EMAIL_FROM:-cribl-audit@example.com}"
TO=""
SUBJECT="Untracked AppIDs Report — $(date +%Y-%m-%d)"
OUTPUT_DIR="/tmp/apmids_report_$$"

# --- parse args --------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--to)      TO="$2";      shift 2 ;;
    -c|--config)  CONFIG="$2";  shift 2 ;;
    -d|--days)    DAYS="$2";    shift 2 ;;
    -f|--from)    FROM="$2";    shift 2 ;;
    --subject)    SUBJECT="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$TO" ]]; then
  echo "ERROR: -t/--to <email> is required" >&2
  exit 1
fi

# --- run audit ---------------------------------------------------------------
mkdir -p "$OUTPUT_DIR"
CSV_FILE="$OUTPUT_DIR/untracked_apmids.csv"

echo "Running audit (last ${DAYS} days)..."
docker run --rm \
  -v "$(realpath "$CONFIG"):/app/config.json:ro" \
  -v "$OUTPUT_DIR:/app/output" \
  -- apmids-blob \
  --config config.json --days "$DAYS" -o "output/untracked_apmids.csv"

MISSING_CSV="$OUTPUT_DIR/untracked_apmids_missing_only.csv"

# --- build email body --------------------------------------------------------
TOTAL=$(tail -n +2 "$CSV_FILE" | wc -l | tr -d ' ')
MISSING=0
if [[ -f "$MISSING_CSV" ]]; then
  MISSING=$(tail -n +2 "$MISSING_CSV" | wc -l | tr -d ' ')
fi

BODY="Untracked AppID Audit — $(date +%Y-%m-%d)
==================================================

Scan window  : last ${DAYS} days
Total apmIds : ${TOTAL}
Untracked    : ${MISSING}

$(if [[ "$MISSING" -gt 0 && -f "$MISSING_CSV" ]]; then
    echo "Untracked apmIds:"
    echo ""
    column -t -s',' "$MISSING_CSV" 2>/dev/null || cat "$MISSING_CSV"
  else
    echo "All apmIds are tracked — no action needed."
  fi)

--
Generated by cribl-audit/send_report.sh"

# --- send email --------------------------------------------------------------
echo "$BODY" | mail -s "$SUBJECT" -r "$FROM" "$TO"

echo "Report sent to ${TO}"

# --- cleanup -----------------------------------------------------------------
rm -rf "$OUTPUT_DIR"
