apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-etn-secret
  labels:
    app: etn-onboarding
    release: {{ .Release.Name }}
type: Opaque
data:
  SECRET_KEY: {{ "change-me-in-production" | b64enc | quote }}
  CRIBL_TOKEN: {{ .Values.env.CRIBL_TOKEN | b64enc | quote }}
  ECE_ES_TOKEN: {{ .Values.env.ECE_ES_TOKEN | b64enc | quote }}
  ETN_PORTAL_API_KEY: {{ .Values.env.ETN_PORTAL_API_KEY | b64enc | quote }}
  HARNESS_API_KEY: {{ .Values.env.HARNESS_API_KEY | b64enc | quote }}
