{{- if and .Values.criblService.enabled (not .Values.criblService.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cribl-service
  labels:
    {{- include "cf.labels" (dict "root" $ "name" "cribl-service") | nindent 4 }}
type: Opaque
data:
  CRIBL_TOKEN: {{ .Values.external.cribl.token | b64enc | quote }}
  CRIBL_USERNAME: {{ .Values.external.cribl.username | b64enc | quote }}
  CRIBL_PASSWORD: {{ .Values.external.cribl.password | b64enc | quote }}
{{- end }}
