{{- if and .Values.eceService.enabled (not .Values.eceService.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ece-service
  labels:
    {{- include "cf.labels" (dict "root" $ "name" "ece-service") | nindent 4 }}
type: Opaque
data:
  ECE_ES_TOKEN: {{ .Values.external.ece.esToken | b64enc | quote }}
  ECE_ES_USERNAME: {{ .Values.external.ece.esUsername | b64enc | quote }}
  ECE_ES_PASSWORD: {{ .Values.external.ece.esPassword | b64enc | quote }}
  ECE_ES_TOKEN_PROD: {{ .Values.external.ece.esTokenProd | b64enc | quote }}
  ECE_ES_USERNAME_PROD: {{ .Values.external.ece.esUsernameProd | b64enc | quote }}
  ECE_ES_PASSWORD_PROD: {{ .Values.external.ece.esPasswordProd | b64enc | quote }}
  ECE_KIBANA_TOKEN: {{ .Values.external.ece.kibanaToken | b64enc | quote }}
  ECE_KIBANA_USERNAME: {{ .Values.external.ece.kibanaUsername | b64enc | quote }}
  ECE_KIBANA_PASSWORD: {{ .Values.external.ece.kibanaPassword | b64enc | quote }}
{{- end }}
