{{- if and .Values.etnOnboarding.enabled (not .Values.etnOnboarding.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-etn-onboarding
  labels:
    {{- include "cf.labels" (dict "root" $ "name" "etn-onboarding") | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.etnOnboarding.secretKey | b64enc | quote }}
  AUTH_LOCAL_USERS: {{ include "cf.etnAuthLocalUsers" . | b64enc | quote }}
  ETN_PORTAL_API_KEY: {{ .Values.etnOnboarding.etnPortalApiKey | b64enc | quote }}
  {{- if .Values.external.postgres.etnDatabaseUrl }}
  DATABASE_URL: {{ .Values.external.postgres.etnDatabaseUrl | b64enc | quote }}
  {{- end }}
{{- end }}
