{{- if and .Values.framework.enabled (not .Values.framework.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cribl-framework-appconfig
  labels:
    {{- include "cf.labels" (dict "root" $ "name" "cribl-framework") | nindent 4 }}
type: Opaque
stringData:
  config.json: |-
{{ .Values.framework.config.content | indent 4 }}
{{- end }}
