{{- if and .Values.framework.enabled (not .Values.framework.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cribl-framework
  labels:
    {{- include "cf.labels" (dict "root" $ "name" "cribl-framework") | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.framework.secretKey | b64enc | quote }}
  ES_DATASTREAM_USERNAME: {{ .Values.external.elasticsearch.datastreamUsername | b64enc | quote }}
  ES_DATASTREAM_PASSWORD: {{ .Values.external.elasticsearch.datastreamPassword | b64enc | quote }}
  ETN_ONBOARDING_TOKEN: {{ .Values.framework.etnOnboardingToken | b64enc | quote }}
  {{- if .Values.external.postgres.frameworkDatabaseUrl }}
  DATABASE_URL: {{ .Values.external.postgres.frameworkDatabaseUrl | b64enc | quote }}
  {{- end }}
{{- end }}
